name: Build Packer Image
description: 'Build PSPi image'
inputs:
  build:
    description: 'Comma seperated list of images to build'
    required: true
  AZCOPY_TENANT_ID:
    description: 'Azure Tenant ID'
    required: true
  AZCOPY_SPA_CLIENT_SECRET:
    description: 'Azure Service Principal Client Secret'
    required: true
  AZCOPY_SPA_APPLICATION_ID:
    description: 'Azure Service Principal Application ID'
    required: true
  

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Login with azcopy
      run: |
        export AZCOPY_AUTO_LOGIN_TYPE=SPN
        export AZCOPY_SPA_APPLICATION_ID=${{ inputs.AZCOPY_SPA_APPLICATION_ID }}
        export AZCOPY_SPA_CLIENT_SECRET=${{ inputs.AZCOPY_SPA_CLIENT_SECRET }}
        export AZCOPY_TENANT_ID=${{ inputs.AZCOPY_TENANT_ID }}
        az login --service-principal -u ${{ inputs.AZCOPY_SPA_APPLICATION_ID }} -p ${{ inputs.AZCOPY_SPA_CLIENT_SECRET }} --tenant ${{ inputs.AZCOPY_TENANT_ID }}

        azcopy list "https://stpspiproduseast001.blob.core.windows.net/pspi6/"
      shell: bash     

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0      

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install fdisk gdisk qemu-user-static libarchive-tools tar parted qemu-utils
      shell: bash

    - name: Install packer-builder-arm
      run: |
        mkdir -p $GITHUB_WORKSPACE/packer/plugins
        cd $GITHUB_WORKSPACE/packer/plugins
        git clone https://github.com/mkaczanowski/packer-builder-arm
        cd packer-builder-arm
        go mod download
        go build -v .
      shell: bash

    - name: Build images
      run: |
        sudo packer build -only ${{ inputs.build }} -var pspi_version=v${{ steps.gitversion.outputs.majorMinorPatch }} "$GITHUB_WORKSPACE/packer/"
      working-directory: packer/plugins/packer-builder-arm
      shell: bash

    - name: Shrink images
      run: |
        wget https://raw.githubusercontent.com/Drewsif/PiShrink/master/pishrink.sh
        chmod +x pishrink.sh
        for i in $(ls *.img)
        do
          sudo ./pishrink.sh -v -Z -a "$i"
        done
      working-directory: packer/plugins/packer-builder-arm
      shell: bash

    - name: Generate sha256 filehash
      run: |
        for i in $(ls *.img.xz)
        do
          sha256sum "$i" | awk '{print $1}' > "$i.sha256"
        done
      working-directory: packer/plugins/packer-builder-arm
      shell: bash

    - name: Upload files to storage account
      run: |
        export AZCOPY_AUTO_LOGIN_TYPE=SPN
        export AZCOPY_SPA_APPLICATION_ID=${{ inputs.AZCOPY_SPA_APPLICATION_ID }}
        export AZCOPY_SPA_CLIENT_SECRET=${{ inputs.AZCOPY_SPA_CLIENT_SECRET }}
        export AZCOPY_TENANT_ID=${{ inputs.AZCOPY_TENANT_ID }}
        az login --service-principal -u ${{ inputs.AZCOPY_SPA_APPLICATION_ID }} -p ${{ inputs.AZCOPY_SPA_CLIENT_SECRET }} --tenant ${{ inputs.AZCOPY_TENANT_ID }}

        for i in $(ls *.img.xz)
        do
          azcopy copy "$i" "https://stpspiproduseast001.blob.core.windows.net/pspi6/$i"
        done

        for i in $(ls *.img.xz.sha256)
        do
          azcopy copy "$i" "https://stpspiproduseast001.blob.core.windows.net/pspi6/$i"
        done
      working-directory: packer/plugins/packer-builder-arm
      shell: bash
      
    - name: Create Release
      if: ${{ inputs.build }} != 'kali_cm4.*' || ${{ inputs.build }} != 'kali_zero2.*'
      uses: softprops/action-gh-release@v0.1.15
      with:
        generate_release_notes: true
        tag_name: v${{ steps.gitversion.outputs.majorMinorPatch }}
        name: Release v${{ steps.gitversion.outputs.majorMinorPatch }}
        draft: true
        fail_on_unmatched_files: true
        files: |
          packer/plugins/packer-builder-arm/*.img.xz
          packer/plugins/packer-builder-arm/*.img.xz.sha256

      

      