name: Build Images

on:
  push: 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install fdisk gdisk qemu-user-static libarchive-tools tar

      - name: Install packer-builder-arm
        run: |
          # mkdir -p $HOME/.config/packer/plugins
          # cd $HOME/.config/packer/plugins
          cd /usr/local/bin
          git clone https://github.com/mkaczanowski/packer-builder-arm
          cd packer-builder-arm
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
          sudo go mod download
          sudo go build -v .

      - name: Packer init
        run: |
          sudo packer init "$GITHUB_WORKSPACE/packer/"

      - name: Build images
        run: |
          sudo packer build "$GITHUB_WORKSPACE/packer/"

      