name: Build Images

on:
  workflow_dispatch:
  push: 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install fdisk gdisk qemu-user-static libarchive-tools tar parted qemu-utils

      - name: Install packer-builder-arm
        run: |
          mkdir -p $GITHUB_WORKSPACE/packer/plugins
          cd $GITHUB_WORKSPACE/packer/plugins
          git clone https://github.com/mkaczanowski/packer-builder-arm
          cd packer-builder-arm
          go mod download
          go build -v .

      - name: Build images
        run: |
          sudo packer build -var pspi_version=$GITHUB_RUN_ID "$GITHUB_WORKSPACE/packer/"
        working-directory: packer/plugins/packer-builder-arm

      - name: Upload images
        uses: actions/upload-artifact@v4
        with:
          name: drop
          path: packer/plugins/packer-builder-arm/*.img.gz

      

      