name: Build Images

on:
  workflow_dispatch:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '.github/**'
      - 'packer/**'
      - 'rpi/drivers/**'
      - 'rpi/configs/**'
      - 'rpi/services/**'
      - 'rpi/scripts/**'

jobs:
  build-drivers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Drivers
        uses: ./.github/actions/build-drivers
        with:
          build: 'drivers.*'
          createRelease: true
  build-packer-images:
    strategy:
      matrix:
        # Resolves to the packer image name
        os: [batocera, raspios, retropie, kali_cm4, kali_zero2]
    runs-on: ubuntu-latest
    needs: build-drivers
    steps:
      - uses: actions/checkout@v4
      
      - name: Build & Publish Images
        id: build-image
        uses: ./.github/actions/build-image
        with:
          build: '${{ matrix.os }}.*'
          AZCOPY_TENANT_ID: ${{ secrets.AZCOPY_TENANT_ID }}
          AZCOPY_SPA_CLIENT_SECRET: ${{ secrets.AZCOPY_SPA_CLIENT_SECRET }}
          AZCOPY_SPA_APPLICATION_ID: ${{ secrets.AZCOPY_SPA_APPLICATION_ID }}
          AZCOPY_STORAGE_ACCOUNT_NAME: ${{ vars.AZCOPY_STORAGE_ACCOUNT_NAME }}
  build-recalbox:
    runs-on: ubuntu-latest
    needs: build-drivers
    steps:
      - uses: actions/checkout@v4

      - name: Build Recalbox
        uses: ./.github/actions/build-recalbox
  build-lakka:
    runs-on: ubuntu-latest
    needs: build-drivers
    steps:
      - uses: actions/checkout@v4

      - name: Build Lakka
        uses: ./.github/actions/build-lakka
