name: Build Images

on:
  push: 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Go 1.21
        uses: actions/setup-go@v5.0.0
        with:
          go-version: '1.21'
        id: go

      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install fdisk gdisk qemu-user-static libarchive-tools tar

      - name: Install packer-builder-arm
        run: |
          mkdir -p $HOME/.config/packer/plugins
          cd $HOME/.config/packer/plugins
          git clone https://github.com/mkaczanowski/packer-builder-arm
          cd packer-builder-arm
          go mod download
          go build -v .
          export PACKER_PLUGIN_PATH=$HOME/.config/packer/plugins

      - name: Packer init
        run: |
          sudo packer init "$GITHUB_WORKSPACE/packer/"

      - name: Build images
        run: |
          sudo packer build "$GITHUB_WORKSPACE/packer/"

      