name: Build Images

on:
  push: 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install fdisk gdisk qemu-user-static libarchive-tools tar

      - name: Install packer-builder-arm
        run: |
          git clone https://github.com/mkaczanowski/packer-builder-arm
          cd packer-builder-arm
          go mod download
          go build -v .


      - name: Build images
        run: |
          sudo packer build "$GITHUB_WORKSPACE/packer/"
        env: 
          PACKER_PLUGIN_PATH: "$GITHUB_WORKSPACE/packer-builder-arm/"

      