name: Build Images

on:
  workflow_dispatch:
  push: 
  pull_request:
    branches:
      - main

jobs:
  build_images:
    strategy:
      matrix:
        os: [batocera, raspios]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        uses: ./.github/actions/build.yml
        with:
          build: '${{ matrix.os }}*'
