name: Build Images

on:
  workflow_dispatch:
  push: 
  pull_request:
    branches:
      - main

jobs:
  build-images:
    strategy:
      matrix:
        os: [batocera, raspios, retropie]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Image
        uses: ./.github/actions/build-image
        with:
          build: '${{ matrix.os }}.*'
