name: Build Images

on:
  workflow_dispatch:
  push: 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install fdisk gdisk qemu-user-static libarchive-tools tar parted qemu-utils

      - name: Install packer-builder-arm
        run: |
          mkdir -p $GITHUB_WORKSPACE/packer/plugins
          cd $GITHUB_WORKSPACE/packer/plugins
          git clone https://github.com/mkaczanowski/packer-builder-arm
          cd packer-builder-arm
          go mod download
          go build -v .

      - name: Build images
        run: |
          sudo packer build -var pspi_version=$GITHUB_RUN_ID "$GITHUB_WORKSPACE/packer/"
        working-directory: packer/plugins/packer-builder-arm

      # - name: Upload images
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: drop
      #     path: packer/plugins/packer-builder-arm/*.img.gz
          
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     draft: false
      #     prerelease: false

      # - name: Upload Release Asset
      #   id: upload-release-asset 
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
      #     asset_path: packer/plugins/packer-builder-arm/*.img.gz
      #     asset_content_type: application/gzip
      #     asset_name: ${{ github.ref }}.img.gz
          
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          # body_path: .github/workflows/RELEASE_FORMAT.txt
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: true
          fail_on_unmatched_files: true
          files: |
            packer/plugins/packer-builder-arm/*.img.gz

      

      