name: Build Drivers

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit SHA1'
        required: false
        default: ''
        type: string
  push: 
  pull_request:
    branches:
      - main

jobs:
  build-drivers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit == '' && github.sha || inputs.commit }}
          fetch-depth: 0
      - name: Build Drivers
        uses: ./.github/actions/build-drivers
        with:
          build: 'drivers.*'