name: Build Images

on:
  push: 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go 1.21
        uses: actions/setup-go@v5.0.0
        with:
          go-version: '1.21'
          check-latest: true
        id: go

      # - name: Get Go dependencies
      #   run: |
      #     go get -v -t -d ./...
      #     if [ -f Gopkg.toml ]; then
      #         curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      #         dep ensure
      #     fi
      #   working-directory: 

      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install fdisk gdisk qemu-user-static libarchive-tools tar

      - name: Install packer-builder-arm
        run: |
          git clone https://github.com/mkaczanowski/packer-builder-arm
          cd packer-builder-arm
          go mod download
          go build -v .

      - name: Build images
        run: |
          sudo packer build "$GITHUB_WORKSPACE/packer/"
        working-directory: "$GITHUB_WORKSPACE/packer-builder-arm/"

      