name: Build Images

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build'
        required: true
        default: '0.0.0'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '.github/**'
      - 'packer/**'
      - 'rpi/drivers/**'
      - 'rpi/configs/**'
      - 'rpi/services/**'
      - 'rpi/scripts/**'

jobs:
  run-gitversion:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.majorMinorPatch }}
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install GitVersion
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      # Determine version
      - name: Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0

  build-drivers:
    runs-on: ubuntu-latest
    needs: run-gitversion
    steps:
      - uses: actions/checkout@v4

      - name: Build Drivers
        uses: ./.github/actions/build-drivers
        with:
          build: 'drivers.*'
          createRelease: true
          version: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || needs.run-gitversion.outputs.version }}

  build-packer-images:
    env:
      VERSION: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || needs.run-gitversion.outputs.version }}
    strategy:
      matrix:
        # Resolves to the packer image name
        os: [raspios, retropie, kali_cm4, kali_zero2]
    runs-on: ubuntu-latest
    needs:
      - build-drivers
      - run-gitversion
    steps:
      - uses: actions/checkout@v4

      - name: Build & Publish Images
        id: build-image
        uses: ./.github/actions/build-packer-image
        with:
          build: '${{ matrix.os }}.*'
          AZCOPY_TENANT_ID: ${{ secrets.AZCOPY_TENANT_ID }}
          AZCOPY_SPA_CLIENT_SECRET: ${{ secrets.AZCOPY_SPA_CLIENT_SECRET }}
          AZCOPY_SPA_APPLICATION_ID: ${{ secrets.AZCOPY_SPA_APPLICATION_ID }}
          AZCOPY_STORAGE_ACCOUNT_NAME: ${{ vars.AZCOPY_STORAGE_ACCOUNT_NAME }}
          version: ${{ env.VERSION }}

  build-buildroot-images:
    strategy:
      matrix:
        image:
          - OS: lakka
            DOWNLOAD_URL: "https://github.com/libretro/Lakka-LibreELEC/releases/download/v5.0/Lakka-RPi4.aarch64-5.0.img.gz"
            COMPRESSED_IMAGE_NAME: "Lakka-RPi4.aarch64-5.0.img.gz"
            IMAGE_NAME: "Lakka-RPi4.aarch64-5.0.img"
            PSPI_IMAGE_NAME: "Lakka5.0-CM4-PSPi6-v${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || needs.run-gitversion.outputs.version }}.img.gz"
            VERSION: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || needs.run-gitversion.outputs.version }}
          - os: recalbox
            DOWNLOAD_URL: "https://upgrade.recalbox.com/latest/download-wizard/rpi4_64/recalbox-rpi4_64.img.xz"
            COMPRESSED_IMAGE_NAME: "recalbox-rpi4_64.img.xz"
            IMAGE_NAME: "recalbox-rpi4_64.img"
            PSPI_IMAGE_NAME: "Recalbox9.1-CM4-PSPi6-v${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || needs.run-gitversion.outputs.version }}.img.gz"
            VERSION: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || needs.run-gitversion.outputs.version }}
          # - os: recalbox
          #   DOWNLOAD_URL: "https://upgrade.recalbox.com/latest/download-wizard/rpizero2/recalbox-rpizero2.img.xz"
          #   COMPRESSED_IMAGE_NAME: "recalbox-rpizero2.img.xz"
          #   IMAGE_NAME: "recalbox-rpizero2.img"
          #   PSPI_IMAGE_NAME: "Recalbox9.1-Zero2-PSPi6-v${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || needs.run-gitversion.outputs.version }}.img.gz"
          #   VERSION: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || needs.run-gitversion.outputs.version }}
          - os: batocera
            DOWNLOAD_URL: "https://updates.batocera.org/bcm2711/stable/last/batocera-bcm2711-bcm2711-39-20240228.img.gz"
            COMPRESSED_IMAGE_NAME: "batocera-bcm2711-bcm2711-39-20240228.img.gz"
            IMAGE_NAME: "batocera-bcm2711-bcm2711-39-20240228.img"
            PSPI_IMAGE_NAME: "Batocera39-CM4-PSPi6-v${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || needs.run-gitversion.outputs.version }}.img.gz"
            VERSION: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || needs.run-gitversion.outputs.version }}
          - os: batocera
            DOWNLOAD_URL: "https://updates.batocera.org/bcm2836/stable/last/batocera-bcm2836-bcm2836-39-20240301.img.gz"
            COMPRESSED_IMAGE_NAME: "batocera-bcm2836-bcm2836-39-20240301.img.gz"
            IMAGE_NAME: "batocera-bcm2836-bcm2836-39-20240301.img"
            PSPI_IMAGE_NAME: "Batocera39-Zero2-PSPi6-v${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || needs.run-gitversion.outputs.version }}.img.gz"
            VERSION: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || needs.run-gitversion.outputs.version }}
    runs-on: ubuntu-latest
    needs:
      - build-drivers
      - run-gitversion
    steps:
      - uses: actions/checkout@v4

      - name: Build & Publish Images
        uses: ./.github/actions/build-buildroot-image
        with:
          os: ${{ matrix.image.OS }}
          download_url: ${{ matrix.image.DOWNLOAD_URL }}
          compressed_image_name: ${{ matrix.image.COMPRESSED_IMAGE_NAME }}
          image_name: ${{ matrix.image.IMAGE_NAME }}
          pspi_image_name: ${{ matrix.image.PSPI_IMAGE_NAME }}
          version: ${{ matrix.image.VERSION }}
          AZCOPY_TENANT_ID: ${{ secrets.AZCOPY_TENANT_ID }}
          AZCOPY_SPA_CLIENT_SECRET: ${{ secrets.AZCOPY_SPA_CLIENT_SECRET }}
          AZCOPY_SPA_APPLICATION_ID: ${{ secrets.AZCOPY_SPA_APPLICATION_ID }}
          AZCOPY_STORAGE_ACCOUNT_NAME: ${{ vars.AZCOPY_STORAGE_ACCOUNT_NAME }}
