name: Build Images

on:
  workflow_dispatch:
  push: 
  pull_request:
    branches:
      - main

jobs:
  build-images:
    strategy:
      matrix:
        # Resolves to the packer image name
        os: [kali]
        # os: [batocera, raspios, retropie, kali]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Image
        uses: ./.github/actions/build-image
        with:
          build: '${{ matrix.os }}.*'
        env: 
          AZCOPY_TENANT_ID: ${{ secrets.AZCOPY_TENANT_ID }}
          AZCOPY_SPA_CLIENT_SECRET: ${{ secrets.AZCOPY_SPA_CLIENT_SECRET }}
          AZCOPY_SPA_APPLICATION_ID: ${{ vars.AZCOPY_SPA_APPLICATION_ID }}
          AZCOPY_AUTO_LOGIN_TYPE: SPN
